version: "3.9"
services:
  postgres:
    image: postgres:14.8
    environment:
      POSTGRES_DB: "travel_app"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
